"""PO Token extraction via Playwright for tubescrape.

YouTube now requires a PO Token (Proof of Origin Token) for InnerTube API calls.
This token is generated by JavaScript running in the browser and cannot be
obtained by httpx alone.

Usage:
    from src._token import get_po_token

    token = get_po_token(proxy="http://user:pass@host:port")  # optional
    # Then inject into InnerTube headers:
    from tubescrape._http import InnerTube
    InnerTube.PO_TOKEN = token  # or set in DEFAULT_HEADERS
"""

import re
import logging
from typing import Optional

logger = logging.getLogger(__name__)


def get_po_token(proxy: Optional[str] = None, timeout: int = 30) -> Optional[str]:
    """Launch headless Chrome via Playwright, visit youtube.com, extract PO Token.

    The PO Token is found in ytcfg.data_ embedded in the page HTML.
    We inject a small script to extract it before the page fully loads.

    Args:
        proxy: Optional proxy URL for the browser (e.g. 'http://user:pass@host:port').
        timeout: Max seconds to wait for token extraction.

    Returns:
        PO Token string, or None if extraction failed.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        logger.error("playwright not installed. Install with: pip install playwright && playwright install chromium")
        return None

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-blink-features=AutomationControlled",
                    "--disable-dev-shm-usage",
                ],
            )
            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                ),
                proxy={"server": proxy} if proxy else None,
                viewport={"width": 1920, "height": 1080},
                locale="en-US",
            )
            page = context.new_page()

            # Navigate to YouTube — the PO Token is embedded in ytcfg
            token = None

            def _extract_token(response):
                nonlocal token
                if "/youtubei/v1/" in response.url:
                    try:
                        data = response.json()
                        # PO Token sometimes appears in API responses
                        token = data.get("xsrf_token") or data.get("po_token") or token
                    except Exception:
                        pass

            page.on("response", _extract_token)

            try:
                page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=timeout * 1000)
                # Inject script to extract ytcfg PO_TOKEN
                token = page.evaluate("""
                    () => {
                        try {
                            // ytcfg.data_ is set by YouTube's JS
                            if (window.ytcfg && window.ytcfg.data_) {
                                return window.ytcfg.data_.PO_TOKEN || null;
                            }
                            // Fallback: search in all script tags
                            const scripts = document.querySelectorAll('script');
                            for (const s of scripts) {
                                const match = s.text.match(/['\"]PO_TOKEN['\"]\\s*:\\s*['\"]([^'\"]+)['\"]/);
                                if (match) return match[1];
                            }
                            return null;
                        } catch(e) {
                            return null;
                        }
                    }
                """)
                # If still None, wait a bit more and try again
                if not token:
                    page.wait_for_timeout(3000)
                    token = page.evaluate("""
                        () => {
                            try {
                                if (window.ytcfg && window.ytcfg.data_) {
                                    return window.ytcfg.data_.PO_TOKEN || null;
                                }
                                const scripts = document.querySelectorAll('script');
                                for (const s of scripts) {
                                    const match = s.text.match(/['\"]PO_TOKEN['\"]\\s*:\\s*['\"]([^'\"]+)['\"]/);
                                    if (match) return match[1];
                                }
                                return null;
                            } catch(e) {
                                return null;
                            }
                        }
                    """)
            except Exception as e:
                logger.warning(f"PO Token extraction failed: {e}")

            browser.close()

            if token:
                logger.info(f"PO Token extracted: {token[:20]}...")
            else:
                logger.warning("PO Token not found in page")

            return token

    except Exception as e:
        logger.error(f"Playwright error: {e}")
        return None


def inject_po_token(token: Optional[str]) -> None:
    """Inject PO Token into tubescrape's InnerTube headers.
    Call after patch_tubescrape() and before any search requests.
    """
    if not token:
        return
    try:
        from tubescrape._http import InnerTube
        # Add PO Token to default headers (used by InnerTube API calls)
        InnerTube.DEFAULT_HEADERS["X-Goog-Page-Id"] = token  # alternative method
        # Some YouTube endpoints expect it in the request context
        if not hasattr(InnerTube, "PO_TOKEN"):
            InnerTube.PO_TOKEN = token
    except ImportError:
        pass
